### ISSUE TITLE
About resolution of dataset.

### ISSUE THREAD

**Issue by Colezwhy** [dreamscene4d/dreamscene4d#7]
Hi dear authors, thank you for your great work!
But I wonder why the resolutions of input video frames are reshaped into square ones (i.e. 512*512)? Is that an obligatory setting or just for simplicity? I observed that when reshaping the videos in DAVIS dataset, the objects in video frames tend to show some distortions and may thus hinder the performance of instance-wise reconstruction. 
![image](https://github.com/user-attachments/assets/45f4c1b6-e33a-42f6-8ad0-61a94f463ec2)
![image](https://github.com/user-attachments/assets/f5d08d2b-cfaa-450b-94b7-8dc725d82f24)
Could you provide me with some ideas on this? Thank you very much.

**Comment by Colezwhy** [comment]
Also, I wonder which part represents the code for 'Camera Motion Estimation'?

**Comment by wenhsuanchu** [comment]
Hello, thanks for the interest in our work!

For Q1. Why are the videos reshaped to a square in the work?

This is merely for convenience issues. We also noticed that this can cause issues with the 3D lifting and it is better to maintain the original aspect as is. However, since the results and numbers were reported under this setting, we decided to keep it as is for better reproducibility. We recommend not doing a square resizing if you want to apply it to your own data.

For Q2. Where is the code for "Camera Motion Estimation"?

We are still cleaning up the code for this part, and we are looking to release this at a later date, as we are a bit busy with another project right now. I'll keep this issue open to keep track of this. Sorry for the wait!

**Comment by Colezwhy** [comment]
> Hello, thanks for the interest in our work!
> 
> For Q1. Why are the videos reshaped to a square in the work?
> 
> This is merely for convenience issues. We also noticed that this can cause issues with the 3D lifting and it is better to maintain the original aspect as is. However, since the results and numbers were reported under this setting, we decided to keep it as is for better reproducibility. We recommend not doing a square resizing if you want to apply it to your own data.
> 
> For Q2. Where is the code for "Camera Motion Estimation"?
> 
> We are still cleaning up the code for this part, and we are looking to release this at a later date, as we are a bit busy with another project right now. I'll keep this issue open to keep track of this. Sorry for the wait!

Thank you for your reply!
