### ISSUE TITLE
How can I get object mesh per frame?

### ISSUE THREAD

**Issue by ojh6404** [dreamscene4d/dreamscene4d#8]
Thanks for great work!

I'm planning to use this framework to extract  3d transformation of object from RGB frames.
For that, I have to extract mesh (or Point Clouds) of object. 

Is there any solution to do this?
If so, I will really appreciate if someone provide me some clues.

**Comment by wenhsuanchu** [comment]
Unfortunately, this is not directly supported out of the box under our current framework, as it is slightly out of scope of the project. However, since the work was built on top of [DreamGaussian4D](https://github.com/jiawei-ren/dreamgaussian4d/blob/bc229beeda74fcadee167a53b4683b1d7662def3/main_4d.py#L378), it might be useful to check how they do it and merge it with the code.
